### ISSUE TITLE
Feature request: talk tags and filenames

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/identified-chimps-site#1]
Would it be possible to include ['tags'], ['metadata']['file'], and ['metadata']['start_time'] in identified-species.json in addition to the IDs?

I've been maintaining a spreadsheet for Chimp ID using the data from the identified-chimps site, and pulling the three additional fields from the talk API one at a time.  With a few hundred subjects this was reasonable, a few thousand, not so much.

**Comment by chrissnyder** [comment]
Running the expanded query now. Should be up in ~10 minutes.

**Comment by brianaharder** [comment]
Awesome, thank you!

One thing, the science team has expressed concern about having the
filenames put in an easily accessible spot, I think due to concern about
being able to locate the cameras, so could you remove that column from the
website view?  They seem to be perfectly fine with the data being
available, and are happy that I'm using it, they just don't want _everyone_
to be able to see it on talk/wherever... despite the fact that anyone who
looks at the sources in their browser can see it.

**Comment by chrissnyder** [comment]
Had forgotten about that. Hidden!

**Comment by brianaharder** [comment]
Much appreciated!  Thanks for your time.
