### ISSUE TITLE
Videos are unsorted despite call to sort them

### ISSUE THREAD

**Issue by jwidness** [zooniverse/identified-chimps-site#11]
I was thinking about adding a sort call to the generate-lists code and noticed there already is one that doesn't seem to be working quite right.  Starting with line 84, it's correctly sorting them by group and species, but the individual videos aren't listed by zooniverse id, they're listed randomly.  It's not immediately clear to me why this should be happening, but I'm guessing it might have to do with the call to species_key on line 87 (i.e. they never get sorted), or maybe the conversion to json on line 95 (i.e. the conversion is losing the sort)?  Regardless, I actually wanted to add code that would sort by filename rather than zoonivese id.  Do you think you could help me figure why it's not sorting?  Then I could add code to sort by filename to my pending pull request.
Thanks so much!

**Comment by jwidness** [comment]
Continuing on this issue, with the new code (which has the same sort call as before) some of the videos are sorted, but some are not, and I really don't know why.  t'd be great to have them all sorted by ID, but even better would be to have them sorted by filename. If we can get the ID sort to work properly, I could add the code to switch it over to filename.

**Comment by adammcmaster** [comment]
@jwidness As far as I can see they're all correctly sorted by ID. Was it just certain sites that weren't being sorted or something?

**Comment by jwidness** [comment]
The sort has me super confused -- yes, many videos in many lists look in order, but generally, parts of every list are out of order.  At Aged Violet, for example, ACP000ekja is _after_ ACP000esyv.

![Imgur](http://i.imgur.com/hgfxp6R.png)

My experience has been that the end of each list is the most likely part to be out of order.

**Comment by jwidness** [comment]
Thanks so much!

**Comment by jwidness** [comment]
Also, fyi, I made a pull request (#15) to sort by filename rather than by zooniverse id.  Hopefully no mistakes, it's just two lines.
