### ISSUE TITLE
Videos with omit tag aren't omitted

### ISSUE THREAD

**Issue by jwidness** [zooniverse/identified-chimps-site#13]
See ACP00083gs in Dawn Bird for example.

**Comment by jwidness** [comment]
Turns out the omit tag isn't the only problem, the bigger issue is that no tags seem to be getting moderator privileges.  I double-checked [mod_tags_for](https://github.com/zooniverse/identified-chimps-site/blob/master/bin/generate-lists.rb#L47) and couldn't spot a problem, maybe you could take a look at it?  As an example of a video that should be affected by mod tags, [ACP000bxn1](https://talk.chimpandsee.org/#/subjects/ACP000bxn1) has a chimp tag by a regular user, and a mod tag of gorilla, so it should only be in the gorilla list, but instead it's in both.
Thanks!

**Comment by jwidness** [comment]
Any chance someone could check on the moderator tags? Thanks!

**Comment by jwidness** [comment]
I wonder if the $ on comments in [line 52](https://github.com/zooniverse/identified-chimps-site/blob/master/bin/generate-lists.rb#L52) shouldn't be there?  Instead maybe it should be

`{:$match => {'comments.user_name' => {:$in => $moderators}}},`

**Comment by adammcmaster** [comment]
@jwidness Yup, that was it!

**Comment by jwidness** [comment]
Awesome, thanks!

**Comment by jwidness** [comment]
Hm, so moving the match earlier actually changed the behavior of the mod_tags function.  The comments need to be unwound before checking usernames, otherwise all the tags on the video get lumped together.  If performance is really the issue, I have some ideas for different edits we could make instead.

**Comment by adammcmaster** [comment]
Ah, no it's not an issue, I was just trying to be efficient :)

I've moved it back to where it was.

**Comment by jwidness** [comment]
Thanks!  But the behavior doesn't seem to have changed even though the list updated.  Could you double check that the code you ran is the latest version with the match lower down?

**Comment by adammcmaster** [comment]
Oops, my mistake. I'd set it to run the specific version I was testing before and I forgot to change it back when I was done. It should run the latest version today.

**Comment by jwidness** [comment]
Great, it looks like it's doing what I expected, thanks!
I made one more pull request, #17 , with just a couple small changes, hopefully that's it for a while.  Thanks for all your help with this!
