### ISSUE TITLE
List not updating

### ISSUE THREAD

**Issue by jwidness** [zooniverse/identified-chimps-site#18]
The identified chimps list hasn't been updating, could someone take a look at it?
Thanks so much!

**Comment by adammcmaster** [comment]
Yup sorry, this is an issue caused by some changes we're making behind the scenes. It should be working again later this week! I'll let you know when it's fixed.

**Comment by jwidness** [comment]
Great, thanks!

**Comment by adammcmaster** [comment]
It should be up to date again now!

**Comment by jwidness** [comment]
Awesome, thanks for getting to that so quickly!
