### ISSUE TITLE
Frosty Sky still included in identified other primates list

### ISSUE THREAD

**Issue by jwidness** [zooniverse/identified-chimps-site#5]
Not sure if this is actually a problem, but I think maybe the science team would want the one Frosty Sky mangabey video (ACP0000ypk) removed from the list.

**Comment by chrissnyder** [comment]
Might be awhile before I can tackle this. PRs accepted!

**Comment by jwidness** [comment]
I thought about what changes might be necessary on the front end to remove that video and I'm not sure that's the best way to do it.  Is it possible to change the status somewhere in the database so that the video is no longer retired?  As far as I know, the science team wants to redo all of Frosty Sky, so I think getting rid of the 7 counters on that video wouldn't be a big deal.
At any rate, even if the video stays on the list, I don't think it's a huge problem.  Very few people look at it -- I think most users aren't that involved, and the ones who are know to stay away from Frosty Sky for now.

**Comment by adammcmaster** [comment]
Pretty sure this is fixed now (by #10 if not before).
