### ISSUE TITLE
Don't query live databases

### ISSUE THREAD

**Issue by parrish** [zooniverse/identified-chimps-site#6]
That's a pretty heavy set of querying to be done.  We shouldn't do it more than necessary.

There's already a backup of this being produced, we should use that instead: zooniverse-data/ouroboros/2015-11-29_chimp_discussions.csv.tar.gz

**Comment by adammcmaster** [comment]
Is this actually causing a problem for anything? I've configured it to only connect to the hidden mongo node for this reason.

**Comment by parrish** [comment]
> I've configured it to only connect to the hidden mongo node for this reason.
> Ah, that's not as bad then.

Pulling the tags from the aggregated CSV would save you ~45 minutes of querying however.

It also raises the question as to why we're producing that file for them if they aren't using it.

**Comment by adammcmaster** [comment]
Just getting around to looking at this properly. Does that discussions export actually contain all the information this would need? We only want to look at complete subjects and I don't see a quick way to filter those from the CSV. Also are the tags in talk being generated only from the counters on each subject? (I'm wondering why some are tagged "chimp" while others are "chimpanzee".)

**Comment by parrish** [comment]
Honestly, with that query running on the read-only slave, it's probably fine (I forgot about this issue entirely, so it's probably not causing performance issues).
