### ISSUE TITLE
Request for changes to the chimp and primate lists

### ISSUE THREAD

**Issue by jwidness** [zooniverse/identified-chimps-site#8]
We'd like to request some changes to the official chimp and primate lists.  @astopy suggested I ask here if it's possible to use hashtags on the videos as part of the inclusion criteria, and specifically if it's possible to use the identity of the tagger as part of the criteria.  Assuming that it is (and correct me if I'm wrong), could you please make the following changes to the official video list?  Thanks so much!

<ol>
<li> For sites with gorillas (confirm with @mimiarandjelovic which sites she would like included, though the current site Restless Star is definitely one), add an official gorilla video list. </li>

<li> Make the inclusion criteria for the gorilla and chimp lists as follows:
 remove the requirement that a video be retired, instead allow any video from an active site

 if there are no tags by a moderator of (#chimp, #gorilla, #non-ape) on the video, then
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if chimp counters >= 2 OR #chimp tag, put in chimp list
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if gorilla counters >= 2 OR #gorilla tag, put in gorilla list (note this isn't an else-if, we'd like the video to show up in both lists until/unless a moderator puts on the correct species tag)

if tagged #chimp by a moderator, put in the chimp list
if tagged #gorilla by a moderator, put in the gorilla list  (again, not else-if)

To be clear, "tags by a moderator" are tags from anyone who has moderator privileges -- we can provide that list if necessary.  Any other tag is a tag from a regular user who does not have moderator privileges.  Also, just FYI, the #non-ape tag is a placeholder right now while we think about what tag we want to use. </li>

<li>Make the inclusion criteria for the other primate list as follows:
 only retired videos (no change from current procedure)

 at least half of the non-blank counters are other primate, i.e. throw out the blanks before calculating if half are other primate </li>

<br><br>
Thanks so much!!  I wish I could be more helpful in actually writing the code, but I don't know how the mongo database is set up.

**Comment by jwidness** [comment]
Just wanted to check in on the status of this.  I (hopefully) made changes to the generate list code to throw out the blanks in #9, but I don't know the format of the mongo db to help too much more :/

**Comment by jwidness** [comment]
I updated my commit to include the test for `blanks != nil` per suggestion from @astopy, but then I think I also have a new idea about the major changes requested above.

In trying to catch all the chimp videos, throwing out the blanks is going to be a big help, but making the threshold be only 2 chimp counters is going to get a lot of false positives, particularly with monkey videos.  I'm hoping to include videos where maybe, for example, 2 people say chimp, 1 says human, 1 says bird, 1 says grey duiker, 1 says other primate (so less than half are chimp counters) -- that video might actually be a chimp.  But I want to exclude cases where 2 say chimp and 7 say other primate -- that is almost certainly a monkey and not a chimp. So long story short, I think we should add another test to the if statement.  I'm thinking maybe asking if 'other-primate' has less than double the number of chimp counters.  Does that make sense?
change this:
 if chimp counters >= 2 OR #chimp tag, put in chimp list
to:
if (chimp counters >= 2 AND other primate counters < 2 \* chimp counters) OR #chimp tag, put in chimp list

And I'm still thinking about how this might affect sites with gorillas.  Maybe we need to sum the gorilla and chimp counters before comparing to the other primate counters?
i.e. if (chimp counters >= 2 AND other primate counters < 2 \* (chimp counters+gorilla counters)) OR #chimp tag, put in chimp list
 if (gorilla counters >= 2 AND other primate counters < 2 \* (chimp counters+gorilla counters)) OR #gorilla tag, put in gorilla list

**Comment by AnLand** [comment]
@jwidness can you provide an example for your suggestion? All false negatives (both primates and chimps) I encountered so far were blanks. Everything else is rather a false positive.

**Comment by jwidness** [comment]
Sorry, I don't understand your question.  You're asking for an example of a video where throwing out the blanks would get it correctly put in the chimp list?  Or one that has fewer than half chimp counters, but is actually a chimp?

**Comment by AnLand** [comment]
Both, I guess. A video that we do not have in the chimps' spreadsheet right now for the reasons you mentioned as this is the "gold standard".

**Comment by jwidness** [comment]
Here's an example of one that didn't make it to the official list because of too many blanks: ACP000b6go.  If you throw away the blanks, the rest of the counters (6 chimp) pretty clearly indicate chimp.

The second thing was more about throwing out the monkey videos than keeping in chimp videos, but ACP00028im is one that would get correctly included if you tested for at least 2 chimp counters AND the other primate counters had to be less than twice the chimp counters.  More importantly, lots of videos with 2 chimp, 7 other primate would correctly _not_ get included, like ACP0003k1b, because there are at least twice as many other primate counters as chimp counters on it.
